travis:
  secure:
    BINSTAR_TOKEN: NFqB5GYfYtH2zlLNS3HHyYylTyRn97kN5Ee8mzfSevDZp97zEsI7Q0047B7+dDLvfo4UCZtxYaCMDSYjRVy1eDTNcT0VWFBAQolQ0/Keb5cVncnNrjVTc0LhGnDaO5ii9dqGYJm86+vr1qhAc4p64iyxmYkKLvp5H8HCm4IgZCHCHxyl+5gWgDnfZIMNQdPk9Ov8ZUJDD8jHFIocLgotEkWadJ7UTZP9TJL5oDr6l3xdF9L0udYydmiQLh+ZI3+UJqqnyUkaCirXrZURO9ti0iHINMesPYPe1CZjb4QdH/j6q+WJvCIv96+e8vz0j3Lz0wJJFcNsXyEa9S/cgufGFXveaH6rIYyiN8FRW4NiwHcIkrMdeq8kwZAZWDNItfokvA9DZLvV7PmRA6GbbQ/nETwuJ+E/cG7pJjRZPfnLt7Oeq0YJ6g7Yj0r6680+xK11UkIQYWVFohWAX6Usa1kpDj2QgoUDFM5jnjT92rJ5DMx65KYAOw+cT8t75Ksi4mPq9WRXhD267s2/pZTJrh43Ue6Q/F6eegjagQv01YemsLQLt0sVrx488kX8tbe6nPTr/Bzb/CNVW2mCwS5R01cc1pyLgJbNeff1h/s9YBN3gLKz6ktVPdvYp1VXvCgorF6perILW0JZSr7SA2DrqSsrfyUtS7jQIT29G/kohuZ9uKA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
