travis:
  secure:
    BINSTAR_TOKEN: YpPWFTov1RhsCN98p3SJQtPoepxz9XMDHUOK1brULbQssOfN/7CsPSV1PvCK/EP4LbzIZu4S3W/8bls+xZkZfu6cSY2ZNFWqBQzv7LRIhn3aVOlo/cOTvCmpkZ3lj85Gzy/wIHe8h98KNenx27rZbbBwoO/Q27BeJ8VzOdnfIPK94hbFek8IVUK2yTmCRNTJgkD8vpIu0CaphxNRP830Ghov0b2ecEm1wlFgpkcjIH8mKb0okFvtuSsxProD2wuxhUDJ70Q1du0KRpHKJesEBRPJMNH+SfsfygkFDgzWcGv8yxnpHFBSQxQV7a54XY0GgIdD5afDYn52xU+7K7UKIth4/2tHxGQ51b/dYE1pdD/JaUv32Mj0T2iAjWspc58gcxqZARHrcawYpAuf7NwYSdkIiJRFovDdA9Df0ynwKHGpVrG9sn+dhX/FkiN0xCGC0IDWO+s452SBVzUOH4mRi5r08NIPTU3XgSAsZ4wningXvrkaqmw0BqIM3jKfbJ3vU66749rSCiuQ9gnvm2V3Zd7VbEz685ys3laq4sAbBRgpBTaZ5SQml7hyKmY/q9arrBn5678R/Aeq8BAkck+PnRn6p3rO7EUkRsGfnV/NWMUfEQ6najzYMElhYTYw9AYvlkDfGLzs7i6xc0vRC//hK/umOEb2bQJg7NemKnmEkiA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
